var fullName = 'DJDRob';
var isCool = false;
var totalPets = 0;
console.log('fullName: ', fullName);
console.log('isCool: ', isCool);
console.log('totalPets: ', totalPets);
console.log('The type of fullName is: ', typeof fullName);
console.log('The type of isCool is: ', typeof isCool);
console.log('The type of totalPets is: ', typeof totalPets);
var unknown = 'unknown';
console.log('unknown: ', unknown);
console.log('The type of unknown is: ', typeof unknown);
var never;
console.log('never: ', never);
console.log('The type of never is: ', typeof never);
